#!/bin/sh

# run_usb.sh - Wrapper for USB gadget configuration

CONFIG_FILE="/tmp/.usb_config"
MAIN_SCRIPT="/etc/init.d/S50usbdevice"  # Update this path

SUPPORTED_FUNCS="adb mtp ums acm uac1 uac2 uvc rndis ntb hid cdrom"

# Clear any existing config
reset_config() {
    echo "# Auto-generated by run_usb.sh" > $CONFIG_FILE
}

# Probe a specific function
probe_function() {
    func=$1
    shift
    
    case $func in
        adb|mtp|acm|uac1|uac2|uvc|rndis|ntb|hid)
            echo "usb_${func}_en" >> $CONFIG_FILE
            ;;
        ums|msc)
            echo "usb_ums_en" >> $CONFIG_FILE
            # Process storage options
            for opt in "$@"; do
                case $opt in
                    file=*)
                        echo "ums_block=${opt#*=}" >> $CONFIG_FILE
                        ;;
                    size=*)
                        echo "ums_block_size=${opt#*=}" >> $CONFIG_FILE
                        ;;
                    ro=1)
                        echo "ums_ro=on" >> $CONFIG_FILE
                        ;;
                    ro=0)
                        echo "ums_ro=off" >> $CONFIG_FILE
                        ;;
                    floppy=0)
                        echo "ums_floppy=off" >> $CONFIG_FILE
                        ;;
                    floppy=1)
                        echo "ums_floppy=on" >> $CONFIG_FILE
                        ;;
                esac
            done
            ;;
        cdrom)
            echo "usb_ums_en" >> $CONFIG_FILE
            echo "ums_block_cdrom=on" >> $CONFIG_FILE
            for opt in "$@"; do
                case $opt in
                    iso=*)
                        echo "ums_block=${opt#*=}" >> $CONFIG_FILE
                        ;;
                esac
            done
            ;;
        *)
            echo "Unsupported function: $func"
            exit 1
            ;;
    esac
}

case "$1" in
    probe)
        shift
        func=$1
        shift
        reset_config
        probe_function $func "$@"
        ;;
    start)
        $MAIN_SCRIPT start
        ;;
    stop)
        $MAIN_SCRIPT stop
        ;;
    status)
        if [ -f $CONFIG_FILE ]; then
            echo "Current configuration:"
            cat $CONFIG_FILE
        else
            echo "No active configuration"
        fi
        
        # Check if USB gadget is running
        if [ -d /sys/kernel/config/usb_gadget/rockchip ]; then
            echo "USB gadget is active"
        else
            echo "USB gadget is not active"
        fi
        ;;
    *)
        echo "Usage: $0 {probe <function> [options]|start|stop|status}"
        echo "Supported functions: $SUPPORTED_FUNCS"
        echo ""
        echo "Function options:"
        echo "  MSC Storage:  file=/path/to/image size=<MB> ro=<0|1> floppy=<0|1>"
        echo "  CD-ROM:       iso=/path/to/image.iso"
        echo ""
        echo "Examples:"
        echo "  $0 probe adb"
        echo "  $0 probe msc file=/data/disk.img size=512"
        echo "  $0 probe cdrom iso=/data/cdimage.iso"
        echo "  $0 probe acm"
        echo "  $0 start"
        echo "  $0 status"
        echo "  $0 stop"
        exit 1
        ;;
esac

exit 0
